import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { sanityClient, urlFor } from '../lib/sanity';
//import styles from '../styles/Home.module.css'

const recipesQuery = `*[_type == "recipe"] {
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({recipes}) {

  return (
    <div>
      <Head>
        <title>cookies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet"/>
      </Head>

      <main className="biscuitBox">
      <h1>Biscuits for you</h1>

      <ul>
      {recipes?.length > 0 && recipes.map((recipe) => (
        <li>
          <Link href="/">
            <a>
              <img src={urlFor(recipe.mainImage)} className="biscuitImage"/>
              <span>{recipe.name}</span>
            </a>
          </Link>
        </li>
      ))}
      </ul>


      </main>
    </div>
  )
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return { props: {recipes}};
}
